spring:
  profiles: 
    active: dev
spring:
  profiles: dev
  application:
    name: springcloud-consumer-dept-80
#Eureka
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
server:
  port: 8202      
spring:
  profiles: dev
  application:
    name: springcloud-consumer-dept-80
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/  
